export const base_url = 'https://pinaupaph-api.vercel.app/api/user'
export const document_url = 'https://pinaupaph-api.vercel.app/api/documents'
export const payment_url = 'https://pinaupaph-api.vercel.app/api/payment'
export const apartment_url = 'https://pinaupaph-api.vercel.app/api/apartment'
export const cctv_url = 'https://pinaupaph-api.vercel.app/api/cctv'